AUTHOR_NAME="Jérémie DECOCK"
AUTHOR_EMAIL="jd.jdhp@gmail.com"
AUTHOR_WEB_SITE="www.jdhp.org"

COPYRIGHT_NOTICE="Copyright (c) 2016,2017 ${AUTHOR_NAME} (${AUTHOR_WEB_SITE})"

DOCUMENT_DATE="1er Janvier 2017"           # TODO
INSTITUTE=""                               # TODO
DOCUMENT_SUBJECT="TODO"                    # TODO
DOCUMENT_KEYWORDS="TODO,TODO"              # TODO

DOCUMENT_TITLE="TODO"                      # TODO
DOCUMENT_SUBTITLE="TODO"                   # TODO
DOCUMENT_FILE_BASE_NAME="TODO_fr"          # TODO

DOCUMENT_GIT_FORGE_ACCOUNT="jdhp-docs"     # TODO
DOCUMENT_GIT_FORGE_REPOSITORY_NAME="TODO"  # TODO

DOCUMENT_GIT_FORGE_DOMAIN="github.com"     # TODO
DOCUMENT_GIT_FORGE_URL="https://${DOCUMENT_GIT_FORGE_DOMAIN}"
DOCUMENT_GIT_FORGE_PROJECT_URL="${DOCUMENT_GIT_FORGE_URL}/${DOCUMENT_GIT_FORGE_ACCOUNT}/${DOCUMENT_GIT_FORGE_REPOSITORY_NAME}"
DOCUMENT_ISSUE_TRACKER_URL="${DOCUMENT_GIT_FORGE_URL}/${DOCUMENT_GIT_FORGE_ACCOUNT}/${DOCUMENT_GIT_FORGE_REPOSITORY_NAME}/issues"

DOCUMENT_WEB_SITE_URL="http://www.jdhp.org/documentation_fr.html#${DOCUMENT_FILE_BASE_NAME}"
DOCUMENT_HTML_URL="http://www.jdhp.org/docs/${DOCUMENT_FILE_BASE_NAME}/${DOCUMENT_FILE_BASE_NAME}.html"
DOCUMENT_PDF_URL="http://www.jdhp.org/dl/pdf/${DOCUMENT_FILE_BASE_NAME}.pdf"

HTML_TMP_DIR="html_tmp"
